apiVersion: v1
kind: Service
metadata:
  name: bugzilla-prod-mysql-service
  labels:
    app: bugzilla-prod-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: bugzilla-prod-mysql
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: bugzilla-prod-mysql-deployment
  labels:
    app: bugzilla-prod-mysql
spec:
  selector:
    matchLabels:
      app: bugzilla-prod-mysql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bugzilla-prod-mysql
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: sl@@23$
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-bugzilla-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-bugzilla-storage
        persistentVolumeClaim:
          claimName: mysql-bugzilla-pv
