apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: bugzilla-prod-bugzilla-deployment
  labels:
    app: bugzilla-prod-bugzilla
spec:
  selector:
    matchLabels:
      app: bugzilla-prod-bugzilla
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bugzilla-prod-bugzilla
        tier: bugzilla
    spec:
      containers:
      - image: kumargaurav522/docker-bugzilla:latest
        name: bugzilla
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          containerPort: 443
        volumeMounts:
        - name: bugzilla-storage
          mountPath: /var/www/html
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "cp -r /opt/app/. /var/www/html"]
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: bugzilla-storage
        persistentVolumeClaim:
          claimName: bugzilla-prod-pv
