---
apiVersion: v1
kind: Service
metadata:
  name: bugzilla-prod-bugzilla-deployment
spec:
  selector:
    app: bugzilla-prod-bugzilla
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      nodePort: 32444
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      nodePort: 32445
      port: 443
      targetPort: 443
